<script>
  import { writable } from "svelte/store";
  import { Field, Poseidon } from 'o1js';

  let privateKey = "";
  let authenticated = false;
  let activeTab = "authentify";
  let verificationStatus = "";
  let alerts = writable([
    { title: "Violence psychologique au travail", text: "Un employé a été victime de harcèlement moral, avec des menaces implicites et des critiques constantes portant atteinte à sa santé mentale. Ce comportement a été ignoré par la direction pendant plusieurs mois." },
    { title: "Corruption dans les contrats publics", text: "Il y a eu des accusations de pots-de-vin dans le cadre de l'attribution des marchés publics, où des fonctionnaires ont favorisé des entreprises spécifiques en échange de paiements illégaux." }
  ]);

  let showModal = false;
  let newAlertTitle = "";
  let newAlertText = "";

  // List of valid commitments for our 5 users
  const VALID_COMMITMENTS = [
    "2734036284392727479853899077762122337623296282371945742738835164904890170311",
    "2321478515762014168559363437710915598412108051241564560118652143711055701834",
    "8666843847536731435524717447634722451056074249632382408282620992874859271444",
    "18065181644694098491884201615695052475542502648859735574683624528755051083823",
    "18913834321776654036051989032765033341429370907386993951960999681382623778011"
  ];

  function computeCommitment(privateKeyStr) {
    try {
      const privateKeyField = Field(privateKeyStr);
      return Poseidon.hash([privateKeyField]).toString();
    } catch (error) {
      throw new Error('Invalid private key format');
    }
  }

  async function validateKey() {
    try {
      const commitment = computeCommitment(privateKey);
      if (VALID_COMMITMENTS.includes(commitment)) {
        authenticated = true;
        activeTab = "readAlerts";
        verificationStatus = "Private key verified successfully!";
      } else {
        authenticated = false;
        verificationStatus = "Invalid private key. This key was not generated by the system.";
      }
    } catch (error) {
      authenticated = false;
      verificationStatus = error.message;
    }
  }

  function openAlertModal() {
    showModal = true;
    newAlertTitle = "";
    newAlertText = "";
  }

  function submitAlert() {
    if (newAlertTitle.trim() && newAlertText.trim()) {
      alerts.update(current => [
        { title: newAlertTitle, text: newAlertText },
        ...current
      ]);
      showModal = false;
    }
  }

  function changeTab(tab) {
    activeTab = tab;
  }
</script>

<style>
  :global(body) {
    background-color: #111;
    color: white;
    font-family: "Times New Roman", sans-serif;
  }

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
  }

  h1 {
    font-size: 2rem;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 2px;
    color: rgb(255, 255, 255);
  }

  .tabs {
    display: flex;
    margin-top: 20px;
  }

  .tab {
    padding: 10px 20px;
    background: #333;
    border-radius: 5px;
    margin-right: 10px;
    cursor: pointer;
  }

  .tab:hover {
    background: #555;
  }

  .tab.active {
    background: #6a747f;
  }

  .auth-box {
    margin-top: 100px;
    background: #222;
    padding: 60px;
    border-radius: 10px;
    box-shadow: 0 4px 10px rgba(255, 255, 255, 0.1);
    text-align: center;
  }

  input, textarea {
    width: 100%;
    padding: 10px;
    border-radius: 5px;
    border: none;
    margin-top: 10px;
    background: #333;
    color: white;
  }

  button {
    background: #007bff;
    color: white;
    border: none;
    padding: 12px 24px;
    margin-top: 15px;
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.3s ease;
  }

  button:hover {
    background: rgb(86, 86, 86);
  }

  .alerts {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 70px;
  }

  .alert {
    background: linear-gradient(145deg, rgba(255, 0, 0, 0.37), rgba(255, 68, 58, 0.58));
    padding: 20px;
    margin-bottom: 40px;
    border-radius: 15px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
    width: 100%;
    max-width: 900px;
    margin-left: auto;
    margin-right: auto;
  }

  .alert h3 {
    font-size: 1.8rem;
    font-weight: bold;
    color: white;
    margin-bottom: 15px;
  }

  .alert p {
    font-size: 1.2rem;
    color: white;
    line-height: 1.6;
  }

  .add-alert {
    font-size: 3rem;
    background: rgba(255, 0, 0, 0.81);
    color: white;
    border-radius: 50%;
    width: 80px;
    height: 80px;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    margin-top: 50px;
    transition: all 0.3s ease;
  }

  .add-alert:hover {
    background: #ff6f47;
  }

  .modal {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.8);
    display: flex;
    justify-content: center;
    align-items: center;
    opacity: 0;
    transform: scale(0.8);
    transition: opacity 0.9s ease, transform 0.9s ease;
  }

  .modal.show {
    opacity: 1;
    transform: scale(1);
  }

  .modal-content {
    background: #222;
    padding: 30px;
    border-radius: 10px;
    width: 50%;
    text-align: center;
  }

  .close {
    position: absolute;
    top: 10px;
    right: 20px;
    font-size: 2rem;
    cursor: pointer;
  }

  .definition {
    font-size: 1.3rem;
    font-style: italic;
    color: rgba(255, 255, 255, 0.7);
    text-align: center;
    margin-top: 40px;
    padding: 10px;
    border-top: 1px solid rgba(255, 255, 255, 0.3);
    position: absolute;
    bottom: 20px;
    width: 100%;
  }

  .definition span {
    font-size: 1.2rem;
    color: rgba(255, 255, 255, 0.8);
  }

  .status-message {
    margin-top: 10px;
    padding: 10px;
    border-radius: 5px;
  }

  .status-message.error {
    background-color: rgba(255, 0, 0, 0.2);
    color: #ff4444;
  }

  .status-message.success {
    background-color: rgba(0, 255, 0, 0.2);
    color: #44ff44;
  }
</style>

<div class="container">
  <h1>Whistleblower</h1>

  {#if !authenticated}
  <div class="auth-box">
    <p>Enter private key:</p>
    <input type="password" bind:value={privateKey} placeholder="Private Key" />
    <button on:click={validateKey}>Authentify</button>
    {#if verificationStatus}
      <div class="status-message {authenticated ? 'success' : 'error'}">
        {verificationStatus}
      </div>
    {/if}
  </div>
  {/if}

  {#if authenticated}
  <div class="tabs">
    <div class="tab {activeTab === 'readAlerts' ? 'active' : ''}" on:click={() => changeTab('readAlerts')}>Read Alerts</div>
    <div class="tab {activeTab === 'alertTab' ? 'active' : ''}" on:click={() => changeTab('alertTab')}>ALERT 🚨</div>
  </div>
  {/if}

  {#if activeTab === 'readAlerts'}
  <div class="alerts">
    {#each $alerts as alert}
      <div class="alert">
        <h3>{alert.title}</h3>
        <p>{alert.text}</p>
      </div>
    {/each}
  </div>
  {/if}

  {#if activeTab === 'alertTab' && authenticated}
  <div class="alerts">
    <div class="add-alert" on:click={openAlertModal}>+</div>
  </div>
  {/if}

  {#if showModal}
    <div class="modal show">
      <div class="modal-content">
        <span class="close" on:click={() => (showModal = false)}>&times;</span>
        <h2>Nouvelle Alerte</h2>
        <input type="text" bind:value={newAlertTitle} placeholder="Titre de l'alerte..." />
        <textarea bind:value={newAlertText} rows="5" placeholder="Détails de l'alerte..."></textarea>
        <button on:click={submitAlert}>Envoyer</button>
      </div>
    </div>
  {/if}

  {#if authenticated}
    <div class="definition">
      <p><strong>whistle-blower</strong><br> 
        <span>[wɪs:əl:bloʊ:ər]</span> <span>- noun</span><br>
        <span style="font-style: italic;">A person who exposes illegal, unethical, or abusive actions within an organization, often at the risk of retaliation.</span>
      </p>
    </div>
  {/if}
</div>
